### ISSUE TITLE
Create Home Page with Access to Four Web Applications

### ISSUE THREAD

**Issue by Lennon0926** [Lennon0926/jp-webapp#13]
# Description 
Develop a home page that provides access to four separate web applications. Each application should be represented by a visually distinct and clickable element on the home page. Consider using icons or labels to clearly indicate the purpose of each application.

Ensure that the home page layout is user-friendly and intuitive, allowing users to easily navigate to the desired application. Consider incorporating responsive design principles to ensure compatibility with various devices and screen sizes.

Additionally, the home page should maintain a cohesive design aesthetic that aligns with the branding of the web applications. Consider using consistent color schemes, typography, and layout elements across the home page and the linked applications.

**Comment by Adriana-Isabel** [comment]
**_Things Added:_**

1. Movable Header.
2. Pop-Up Menu.
3. Logo.
4. Images that are clickable to take you to the desired Web App.
5. Clickable Web App names.


 **_Still Working On:_**

1. Search bar and button.
2. Adding visuals.

**Comment by Adriana-Isabel** [comment]
DONE

**Comment by Adriana-Isabel** [comment]
DONE
