### ISSUE TITLE
Formulario JP-541 Creation

### ISSUE THREAD

**Issue by EdzelOrtiz** [Lennon0926/jp-webapp#18]
Recreate the Form JP-541 using html, css, and javascript allowing users to input their information in the webpage.

The form is available here -> https://jp.pr.gov/cuestionarios/
The category of the form is through Balanza de Pagos
JP-304 – Relación de Aportaciones Federales Aprobadas, Recibidas y Gastadas

**Comment by Adriana-Isabel** [comment]
DONE
